project:
  type: website
  output-dir: docs
website:
  title: "Mikroøkonomi (SFB10816)"
    #repo-url: https://github.com/joernih/https://github.com/joernih/SFB10816Mikrooekonomi
    #site-url: https://github.com/joernih/https://joernih.github.io/SFB10816Mikrooekonomi/
  reader-mode: false
  repo-actions: [edit]
  navbar:
    left:
      - text: "Timeplan"
      - text: "Forelesninger"
      - text: "Seminar"
      - text: "Arbeidskrav"
      - text: "Anbefalte oppgaver"
      - text: "Utskrifter"
      - text: "Endringslog"


