project:
  type: website
  render:
    - "index.qmd"
    - "timeplan/timeplan.qmd"
    - "forelesninger/notater.qmd"
      #    - "forelesninger/presentations_hiof.Rmd"
    - "oppgaver/arbeidskrav.qmd"
    - "seminar/posts.qmd"
    - "seminar/oppgaver/*.qmd"
    - "utskrifter/utskrifter.qmd"
    - "log.qmd"

website:
  title: "Mikroøkonomi (SFB10816)"
  reader-mode: false
  page-footer: 
       left: "Jørn I. Halvorsen (jorn.i.halvorsen at hiof.no)" 
       right: 
         - icon: github
           href: https://github.com/joernih/OEKA201ProgrammingWebPage
format:
  html:
    theme: zephyr
    toc: true

# forelesninger/timeplan.R
# _quarto-internal.yml
# _quarto-external.yml

