project:
  type: website
  render:
    - "index.qmd"
    - "timeplan/timeplan.qmd"
    - "forelesninger/notater.qmd"
    - "oppgaver/oppgaver.qmd"
    - "seminar/oppgaveseminar.qmd"
    - "utskrifter/utskrifter.qmd"
    - "log.qmd"

website:
  title: "Mikroøkonomi (SFB10816)"
  repo-url: https://github.com/joernih/https://github.com/joernih/SFB10816Mikrooekonomi
  site-url: https://github.com/joernih/https://joernih.github.io/SFB10816Mikrooekonomi/
  reader-mode: false
  repo-actions: [edit]
  page-footer: 
       left: "Jørn I. Halvorsen (jorn.i.halvorsen at hiof.no)" 
       right: 
         - icon: github
           href: https://github.com/joernih/OEKA201ProgrammingWebPage
format:
  html:
    theme: zephyr
    toc: true

# forelesninger/notater.qmd
# _quarto-internal.yml
# _quarto-external.yml
