project:
  type: website
  output-dir: docs

website:
  title: "Mikroøkonomi (SFB10816)"
  navbar:
    left:
      - text: "Forside"
        href: index.qmd
      - text: "Timeplan"
        href: timeplan.qmd

format:
  html:
    theme: zephyr
    toc: true
