project:
  type: website
  render:
    - "index.qmd"
    - "timeplan/timeplan.qmd"
    - "forelesninger/notater.qmd"
    - "forelesninger/allenotater.qmd"
    - "forelesninger/presentations_hiof.Rmd"
    - "oppgaver/eksamensoppg.qmd"
    - "oppgaver/oppgaver.qmd"
    - "oppgaver/arbeidskrav.qmd"
    - "seminar/posts.qmd"
    - "!seminar/oppgaver/abc.qmd"
    - "seminar/oppgaver/*.qmd"
    - "utskrifter/utskrifter.qmd"
    - "log.qmd"
    - "teknisk.qmd"
    - "abc2.qmd"

website:
  title: "Mikroøkonomi (SFB10816)"
  reader-mode: false
  page-footer: 
       left: "Jørn I. Halvorsen (jorn.i.halvorsen at hiof.no)" 
format:
  html:
    theme: default
    toc: true
# Tasks internal
# forelesninger/timeplan.R
# _quarto-internal.yml
# _quarto-external.yml
# data-raw/metadata.json
# Tasks:
# Ukenr Regneverksted
# Numerering av figurer
