project:
  type: website
  output-dir: docs
website:
  title: "Mikroøkonomi (SFB10816)"
    #repo-url: https://github.com/joernih/https://github.com/joernih/SFB10816Mikrooekonomi
    #site-url: https://github.com/joernih/https://joernih.github.io/SFB10816Mikrooekonomi/
  reader-mode: false
  navbar:
    left:
      - text: "Timeplan"
        href: "timeplan/timeplan.qmd"
      - text: "Forelesninger"
        menu:
          - text: "Praktisk informasjon"
            href: "forelesninger/notater.qmd"
          - text: "Forelesning 1: Introduksjon til mikroøkonomi"
            href: "forelesninger/notater.html#/kapittel-1-introduksjon-til-mikroøkonomi.-overblikk-over-fulllkomen-konkurranse"
          - text: "Forelesning 2-3: Introduksjons til produksjonsteori. Produksjonsteori på kort sikt"
            href: "forelesninger/notater.html#/kapittel-4-5-og-6-innledning-til-produsentteorien"
          - text: "Forelesning 3-4: Introduksjons til produksjonsteori. Produksjonsteori på lang sikt"
            href: "forelesninger/notater.html#/kapittel-4-5-og-6-produksjonsteori-p%C3%A5-lang-sikt"
          - text: "Forelesning 5: Konsumentteori"
            href: "forelesninger/notater.html#/kapittel-7-konsumentteori"
          - text: "Forelesning 6: Konsumentens øknomiske adferd i gode- og arbeidsmarkedet"
            href: "forelesninger/notater.html#/kapittel-8-konsumentens-økonomiske-adferd-i-gode--og-arbeidsmarkedet"
          - text: "Forelesning 7: Fullkommen konkurranse"
            href: "forelesninger/notater.html#/kapittel-9-markedsteori-fullkommen-konkurranse"
          - text: "Forelesning 8: Monopol"
            href: "forelesninger/notater.html#/kapittel-10-markedsteori-ufullkommen-konkurranse---monopol"
      - text: "Oppgaver"
        menu:
          - text: "Anbefalte oppgaver"
            href: "oppgaver/oppgaver.qmd"
          - text: "Seminar"
            href: "seminar/posts.qmd"
          - text: "Arbeidskrav"
            href: "oppgaver/arbeidskrav.qmd"
          - text: "Tidligere eksamensoppgaver"
            href: "oppgaver/eksamensoppg.qmd"
      - text: "Utskrifter"
        href: "utskrifter/utskrifter.qmd"
      - text: "Endringslog"
        href: "log.qmd"
page-footer: 
     right: 
       - icon: github
         href: https://github.com/joernih/OEKA201ProgrammingWebPage
