project:
  type: website
  render:
    - "index.qmd"
    - "timeplan/timeplan.qmd"
    - "forelesninger/notater.qmd"
    - "forelesninger/allenotater.qmd"
    - "forelesninger/presentations_hiof.Rmd"
    - "forelesninger/repetisjonsnotat.qmd"
    - "oppgaver/eksamensoppg.qmd"
    - "oppgaver/oppgaver.qmd"
    - "oppgaver/arbeidskrav.qmd"
    - "seminar/posts.qmd"
    - "!seminar/oppgaver/abc.qmd"
    - "seminar/oppgaver/*.qmd"
    - "forelesninger/utskrifter.qmd"
    - "log.qmd"
    - "teknisk.qmd"
    - "abc2.qmd"

website:
  title: "Mikroøkonomi (SFB10816)"
  reader-mode: false
  page-footer: 
       left: "Jørn I. Halvorsen (jorn.i.halvorsen at hiof.no)" 
format:
  html:
    theme: default
    toc: true
########################################################################
# oppgaver/arbeidskrav.qmd
# Tasks internal
# forelesninger/timeplan.R
# _quarto-internal.yml
# _quarto-external.yml
########################################################################
# Legge ut flere eksamensoppgaver
# 2022 Mai, HIOF oppgave 2
# /home/joernih/homepageJIH/nonpublic/templates/mikro/Arbeidskrav_SFB10816_Mikro_2024_V.qmd
