project:
  type: website
  render:
    - "index.qmd"
    - "kladd.qmd"
    - "timeplan/timeplan.qmd"
    - "forelesninger/notater.qmd"
    - "forelesninger/allenotater.qmd"
    - "forelesninger/presentations_hiof.Rmd"
    - "forelesninger/repetisjonsnotat.qmd"
    - "oppgaver/eksamensoppg.qmd"
    - "oppgaver/oppgaver.qmd"
    - "oppgaver/arbeidskrav.qmd"
    - "seminar/posts.qmd"
    - "!seminar/oppgaver/abc.qmd"
    - "seminar/oppgaver/*.qmd"
    - "forelesninger/utskrifter.qmd"
    - "log.qmd"
    - "teknisk.qmd"
    - "eksamensoppgaver/qmdconvert/Eksamen_SFB10816_2022_V.Rmd"
    - "eksamensoppgaver/qmdconvert/Eksamen_SFB10816_Mikro_2023_V.qmd"
    - "eksamensoppgaver/qmdconvert/Eksamen_SFB10816_Mikro_2023_H_K.qmd"

website:
  title: "Mikroøkonomi (SFB10816)"
  reader-mode: false
  page-footer: 
       left: "Jørn I. Halvorsen (jorn.i.halvorsen at hiof.no)" 
format:
  html:
    theme: default
    toc: true
########################################################################
# Lenke
# git remote set-url origin https://$GIT_PAT@github.com/joernih/SFB10816Mikrooekonomi.git
# /home/joernih/teaching/SFB10816Mikrooekonomi
