project:
  type: website
  render:
    - "index.qmd"
    - "kladd.qmd"
    - "timeplan/timeplan.qmd"
    - "forelesninger/notater.qmd"
    - "forelesninger/allenotater.qmd"
    - "forelesninger/presentations_hiof.Rmd"
    - "forelesninger/repetisjonsnotat.qmd"
    - "oppgaver/eksamensoppg.qmd"
    - "oppgaver/oppgaver.qmd"
    - "oppgaver/arbeidskrav.qmd"
    - "seminar/posts.qmd"
    - "!seminar/oppgaver/abc.qmd"
    - "seminar/oppgaver/*.qmd"
    - "forelesninger/utskrifter.qmd"
    - "log.qmd"
    - "teknisk.qmd"
    - "abc2.qmd"
    - "eksamensoppgaver/qmdconvert/Eksamen_SFB10816_2022_V.Rmd"
    - "eksamensoppgaver/qmdconvert/Eksamen_SFB10816_Mikro_2023_V.qmd"
    - "eksamensoppgaver/qmdconvert/Eksamen_SFB10816_Mikro_2023_H_K.qmd"

website:
  title: "Mikroøkonomi (SFB10816)"
  reader-mode: false
  page-footer: 
       left: "Jørn I. Halvorsen (jorn.i.halvorsen at hiof.no)" 
format:
  html:
    theme: default
    toc: true
########################################################################
# Lenke
# https://hiof.sharepoint.com/sites/kvalitetsrapporter/Dokumenter/Forms/AllItems.aspx?id=%2Fsites%2Fkvalitetsrapporter%2FDokumenter%2FEmnerapporter%2FFakultet%20for%20informasjonsteknologi%2C%20ingeni%C3%B8rfag%20og%20%C3%B8konomi%2FInstitutt%20for%20%C3%B8konomi%2C%20innovasjon%20og%20samfunn%2F%C3%98konomi%20og%20administrasjon%20bachelor%2F2024%20V%C3%A5r&viewid=00000000%2D0000%2D0000%2D0000%2D000000000000
########################################################################
