project:
  type: website
  render:
    - "index.qmd"
    - "timeplan.qmd"
    - "forelesninger/notater.qmd"
    - "arbeidskrav.qmd"
    - "oppgaver.qmd"
    - "utskrifter.qmd"
    - "log.qmd"

# forelesninger/notater.qmd
# _quarto-internal.yml
# _quarto-external.yml


