---
title: "Seminar 5: Markedsteori: Fullkommen konkurranse"
format:
  html:
    toc: false
    css: css/OFF.css
---

Uke xx, ansvarlig xxx

# Fullkommen konkurranse

a. Markedet for moteklær kan studeres som et frikonkurransemarked. Hva menes med markedsmekanismen og likevekt i dette frikonkurransemarkedet? Illustrer grafisk og knytt forklaringer til den grafiske presentasjonen.
<div class="sol">
Se læreboka figur 3.5. Man bør gjengi forutsetningene for markedsformen, særlig viktig er forutsetningene om pristageradferd, fri etablering og ingen eksterne effekter. Markedstilbudskurven gjenspeiler bedriftenes grensekostnadskurver og er stigende i pris, fordi høyere pris gir rom for større produksjon da grensekostnadene er økende i pris. Etterspørselskurven er fallende i pris da lavere pris på et gode gjør godet relativt sett billigere sammenlignet med andre goder, slik at konsumentene på marginen vil etterspørre mer av det aktuelle godet. Dette er substitusjonseffekten. I tillegg vil prisreduksjonen gi konsumentene økt kjøpekraft, og for noen goder vil dette, isolert sett, gi økt etterspørsel. Selv om godet er mindreverdig, vil totalvirkningen av en prisreduksjon på et gode være en økning i etterspørselen etter det samme godet.  
<br>
Ta utgangspunkt i en pris lavere likevektpeis, da har vi et etterspørselsoverskudd, og forklar hvordan prisene fører markedet tilbake til likevekt, hvor tilbud er lik etterspørsel. Gjør deretter det samme med en pris høyere enn likevektspris, da har vi et tilbudsoverskudd.
<br>
Markedsmekanismen er knyttet til den rollen som prisene og ubalanse mellom tilbud og etterspørsel spiller for å føre markedet tilbake til likevekt. Det er dette som skal forklares. 
</div>
a. Blant annet på grunn av koronakrisen, har etterspørselskurven etter moteklær skiftet kraftig innover. Forklar og vis grafisk hvilke konsekvenser dette har for den nye likevekten på markedet.
<div class="sol">
Poenget her er at markedet via prisendringer kommer tilbake til likevekt etter at etterspørselskurven har skiftet innover. Ved den «gamle» prisen har man da et midlertidig tilbudsoverskudd, med pris over likevektspris. Prisene presses nedover, lagrene reduseres, og man kommer til en ny likevekt med lavere priser og lavere omsatt kvantum av moteklær.
</div>
a. Anta at markedet midlertidig er ute av likevekt på grunn av etterspørselssvikt. Illustrer ulikevekten grafisk og knytt forklaringer til figuren. Forklar hvordan man kan komme tilbake til likevekt.
<div class="sol">
Poenget her er at markedet via prisendringer kommer tilbake til likevekt etter at etterspørselskurven har skiftet innover. Ved den «gamle» prisen har man da et midlertidig tilbudsoverskudd, med pris over likevektspris. Prisene presses nedover, lagrene reduseres, og man kommer til en ny likevekt med lavere priser og lavere omsatt kvantum av moteklær.
</div>
a. Anta at produsentene av moteklær inngår en samarbeidsavtale om å redusere produksjonen. Anta videre at noen av aktørene ikke overholder produksjonsavtalen. Hvordan påvirker dette muligheten til å komme tilbake til likevekt?
<div class="sol">
Dersom en, eller flere av aktørene, bryter et prissamarbeid og øker sin produksjon, vil det trolig ha en liten effekt på markedspris og markedsomsetning. I frikonkurranse er det jo svært mange tilbydere som hver for seg har en marginal innflytelse på markedspris og omsetning. Men når én aktør først bryter samarbeidet, og tjener på det, vil mange andre også bli fristet til å gjøre det samme. Hver enkelt aktør vil jo tjene på dette, under forutsetning av at alle andre følger avtalen. Dersom alle, eller mange av tilbyderne, bryter avtalen er vi tilbake i frikonkurranseløsningen slik vi fant den i oppgave b.   
</div>
a. Etterspørselskurven på frikonkurransemarkedet er gitt ved følgende uttrykk:$x^d= 20-p$. Tilbudet er gitt ved  
$x^s=3p$. I dette tilfellet angir $x$ mengde og $p$ er lik pris. Finn likevekten i markedet og illustrer svaret ditt grafisk.
<div class="sol">
Vi ser at likevektspris blir lik 5 kr og likevektsmengde blir lik 15. I diagrammet har vi tegnet inn en fallende etterspørselskurve. Skjæringspunktet må markeres eksplisitt. Vi har også en stigende tilbudskurve som starter i origo. 
Likevekten finner vi matematisk ved å sette etterspørsel lik tilbud, og først løse med hensyn på p. Deretter ser vi verdien for p (=5) inn i for eksempel etterspørselskurven og finner likevektmengden (x=15). 
</div>
a. Definer og kalkuler produsent- og konsument overskuddet i likevekt. Forklar hvorfor det samfunnsøkonomiske overskuddet maksimeres i dette tilfellet?
<div class="sol">
Konsumentoverskuddet (KO) i et marked er lik konsumentenes samlede, maksimale betalingsvilje minus det de faktisk må betale. KO er et mål på konsumentens velferd. Grafisk angis det ved området under etterspørselskurven og over prisen frem til likevektsmengden 15.  Det beregnes som arealet av trekanten: 
$$
KO=\frac{15\cdot (20-5)}{2}=112.50  
$$
Produsentoverskudd (PO) er definert som pris minus det minste produsentene må ha for å være villige til å produsere. Vi finner det som areal under prisen og over tilbudskurven (som er lik summen av alle bedrifters grensekostnadskurver). 
$$
PO=\frac{(15\cdot 5)}{2}=37,5. 
$$
PO er dermed lik pris minus grensekostnader i produksjonen av de omsatte enhetene. 
<br>
Samfunnsøkonomisk overskudd (SØO) er lik summen av KO og PO i dette tilfellet. Vi ser at SØO=150 kroner. 
<br>
Det samfunnsøkonomiske overskuddet maksimeres fordi marginal betalingsvillighet er lik grensekostnadene i produksjon for den siste enheten som omsettes. Marginal betalingsvillighet defineres som det konsumentene er villig til å betale for en ekstra enhet av godet. Dersom vi produserer en enhet mindre enn 15 enheter vil den marginale betalingsviljen være høyere enn grensekostnadene, og det samfunnsøkonomiske overskuddet kan økes ved å øke produksjonen med en enhet. Dersom vi produserer en enhet mer enn 15, vil grensekostnadene i produksjon være høyere enn den marginale betalingsvilligheten. Det koster altså mer å produsere den siste enheten enn det konsumentene er villig til å betale for den. Vi kan dermed øke det samfunnsøkonomiske overskuddet ved å redusere produksjonen med en enhet. Frikonkurranselikevekten maksimerer dermed det samfunnsøkonomiske overskuddet. 
</div>
a. Anta at det pålegges en stykkskatt lik 4 kroner per produsert enhet. Finn den nye likevekten.
<div class="sol">
En avgift vil ha den samme virkning på omsatt kvantum, uavhengig av om den blir pålagt produsentene eller konsumentene. Vi antar her at avgiften pålegges produsentene, noe som betyr at tilbudskurven skifter oppover (venstreskift). For hver solgt enhet, må nå konsumentene betale den tidligere prisen (uten avgiften) tillagt avgiften ($p^D$). Ny etterspørselsfunksjon på prisform: $p^D=20-x^D$ Ny tilbudsfunksjon blir: $p^S=\frac{1}{3}x^S$ . Likevektsbetingelsen er den samme: $x^D=x^S=x$  I tillegg har vi ligningen for sammenhengen mellom konsumentprisen ($p^D$) og produsentprisen ($p^S$). Dette er jo lik stykkskatten (t): 
$$
p^D = p^S + 4
$$
Vi setter inn dette uttrykket i tilbudsfunksjonen, og vi har dermed en ligning og en ukjent som er lik konsumentprisen: 
$$
20-x=(1/3)x + 4 \\
x = 12
$$
Setter likevektsmengden inn i etterspørselsfunksjonen: 
$$
p^D=20–12=8 
$$
Mens for tilbudsfunksjonen
$$
p^S=(1/3)\cdot 12=4 \\
$$
</div>
a. Hva blir konsument- og produsentoverskuddet i dette tilfellet? Hvilke konsekvenser får
skatten for samfunnsøkonomisk overskudd? Forklar og illustrer svaret ditt med
beregninger.
Hva blir konsument- og produsentoverskuddet i dette tilfellet? Hvilke konsekvenser får
skatten for samfunnsøkonomisk overskudd? Forklar og illustrer svaret ditt med
beregninger.
<div class="sol">
KO og PO blir redusert i dette tilfellet. KO er lik maksimal betalingsvilje minus det
man betaler. Det betyr at KO = $(12\cdot 12)/2=72$ kroner. $PO=(4\cdot 12)/2=24$. I tillegg så
betaler man skatt til myndighetene. Total skatt er lik 48 kroner ($4 \cdot 12$). SØO blir
dermed 72+24+48=144 kroner. Reduksjonen i SØO er lik 6 kroner. Det er dette som
er samfunnsøkonomiske tap ved skatt, og er verdien (maksimal betalingsvillighet
minus grensekostnader) av alle de enhetene man ikke produserer sammenlignet med
frikonkurranselikevekt. Vi kan alternativt beregne dødvektstapet som (4*3)/2=6
kroner.
</div>
a. Hvem bærer den minste andelen av skattebyrden? Begrunn svaret ditt.
<div class="sol">
I dette tilfellet bærer konsumentene den største skattebyrden, mens produsenten bærer den minste delen. Konsumentene bærer 3 kroner (de må betale 3 kroner mer for en enhet), mens produsentene bærer 1 krone (de får 1 krone mindre betalt per enhet). Det er den som har den mest uelastiske kurven i likevektpunktet før skatt som bærer den største andelen. Konsumentens etterspørselskurve er dermed mer prisuelastisk enn det tilbudskurven er. Dette kan vi vise eksplisitt ved å beregne de respektive priselastisitetene. Priselastisiteten definerer vi som tilnærmet lik den prosentvise endringen i etterspørselen (eventuelt tilbudet) av et gode som følge av prosentvis endring i prisen på godet. 
</div>
a. Begrunn hvorfor de totale skatteinntektene ikke er en del av det samfunnsøkonomiske tapet ved skatt.
<div class="sol">
Dødvektstapet på grunn av skatt er lik verdien av det som ikke produserer på grunn av at skatten skaper en kile mellom konsumentpris og produsentpris, vi har ikke likhet mellom marginal betalingsvillighet og grensekostnader i produksjon.  Selve skatteinntektene er en overføring fra konsumentene og produsentene i privat sektor til det offentlige, Skatteinntektene brukes til å finansiere offentlig sektor. Dette er altså en del av det samfunnsøkonomiske overskuddet på linje med KO og PO. 
</div>


