---
title: "Seminar 2: Matematikk for mikroøkonomi"
format:
  html:
    enable_js: true
    toc: true
    toc-depth: 4
    #0css: css/OFF.css
# ../../arkiv/fasitmatterepetisjon.pdf
---


```{r, echo=F}
md <- jsonlite::fromJSON(paste0(rprojroot::find_rstudio_root_file(),"/data-raw/metadata.json"))
fdm <- paste0(rprojroot::find_rstudio_root_file(),'/seminar/oppgaver/script/mate.py')
reticulate::source_python(fdm)
eqpar <- list(meql=reticulate::py$modeql,meqs=reticulate::py$modeqs)
eql <- eqpar$meql
```

Uke `r md$regnv$sem2[2]`, ansvarlig: `r md$regnv$ansv[2]`
Fredag kl. 12:15-14:00

## Del I: Modeller i mikroøkonomi
a. ) Hva menes med en økonomisk modell?
<p class="answer hidden">
En forenklet beskrivelse av virkeligheten. Bygger pr. definisjon på forutsetninger.
Virkeligheten er kompliser, forenklingen gjør at vi kan rense vekk momenter som vi tror ikke har noen spesiell innvirkning på vårt spørsmål.
</p>
a. ) Hva er forskjellen mellom *eksogene* og *endogene* variabler i en økonomisk modell?
<p class="answer hidden">
I mikroøkonomi er endogene variable er de variablene som blir forklart av modellen. Eksogene variable er de variablen som inngår i modellen, men blir bestemt utenfor modellen.
</p>
a. ) Hva vil det si å utføre *komparativ stikk* i en økonomisk modell?
<p class="answer hidden">
Innebærer å analysere effekten av en isolert endring i en eller flere variabler (vanligvis ved bruk av derivasjon eller differensiering) i modellen og analysere hvordan dette påvirker de økonomiske resultatene.
</p>

## Del II: Brøkregning og derivasjon
### Brøkregning
Forenkl disse uttrykkene

a. ) $$x^2 \cdot x^3$$
<p class="answer hidden">
$$x^{2+3}=x^{5}$$
</p>
a. ) $$x \cdot x^4$$
<p class="answer hidden">
$$x^{1}x^{4}=x^{1+4}=x^{5}$$
</p>
a. ) $$y+y$$
<p class="answer hidden">
$$2y$$
</p>
a. ) $$`r eql$op1d[1]`$$
<p class="answer hidden">
$$yy+y=y(y+1)$$
</p>
a. ) $$`r eql$op1e[1]`$$
<p class="answer hidden">
$$x_1^{0.5}x_1^1+x_1^{0.5}x_2^1=x_1^{1.5}+x_1^{0.5}x_2$$
</p>
a. ) $$\frac{1}{x_1} \cdot x_1^3$$
<p class="answer hidden">
$$\frac{x_1^{3}}{x_1^1}=x_1^{3-1}=x_1^{2}$$
</p>
a. ) $$`r eql$op1g[1]`$$
<p class="answer hidden">
$$(\frac{x_1}{x_2})^{3}$$
</p>

Løs for $y$:

a. ) $$y^2 =`r eql$op2a[1]`$$
<div class="answer hidden">
$$\sqrt{y^2}=\sqrt{ab}$$ 
$$y=\sqrt{ab}$$ 
</div>
a. ) $$y^{0.5}=`r eql$op2b[1]`$$
<div class="answer hidden">
$$(y^{0.5})^2=(a+b)^2$$
$$y=(a+b)^2$$
</div>


### Derivasjon
### En variabel
Deriver med hensyn på $x$:

a. ) $$`r eql$op3a[1]`$$
<div class="answer hidden">
$$f'(x) = 12x^2 $$
</div>
a. ) $$`r eql$op3b[1]`$$
<div class="answer hidden">
$$f'(x) = 20x^4-6x^{-4}$$
</div>
a. ) $$\frac{1}{6}x^6a$$
<div class="answer hidden">
$$f'(x) = x^5a$$
</div>
a. ) $$\frac{1}{6}x^6+a $$
<div class="answer hidden">
$$f'(x) = x^{5}$$
</div>
a. ) $$\frac{5x}{2x^2}$$
<div class="answer hidden">
$$f'(x) = \frac{52x^2-5x4x}{(2x^2)^2}=\frac{10x^2-20x^2}{(2x^4}=\frac{-5x}{2x^2}$$
</div>

### To variabler
Deriver med hensyn på $x$ og $y$:

a. ) $$`r eql$op3f[1]`$$
<div class="answer hidden">
$$f'_x(x,y)=20x^3$$
$$f'_y(x,y)=1.5y^{-0.5}$$
</div>
a. ) $$`r eql$op3g[1]`$$
<div class="answer hidden">
$$f'_x(x,y)=x+y^{0.5}$$
$$f'_y(x,y)=0.5xy^{-0.5}$$
</div>
a. ) $$3x^{1/6}y^{2}+y^{1/3}x^{3}$$
<div class="answer hidden">
$$f'_x(x,y)=\frac{1}{2}x^{-5/6}y^2+3y^{1/3}x^2$$
$$f'_y(x,y)=6x^{1/6}y+\frac{1}{3}y^{-2/3}x^3$$
</div>

Deriver med hensyn på $x_1$ og $x_2$:

a. ) $$3x_1^{1/6}+x_2^{1/3}$$
<div class="answer hidden">
$$f'_x(x_1,x_2)=\frac{1}{2}x_1^{-5/6}$$
$$f'_y(x_1,x_2)=\frac{1}{3}x_2^{-2/3}$$
</div>

### Diffrensiering
Ta utgangspunkt i funksjonen 
$$
\overline{x} = f(x_1,x_2)
$$
Hvor $\overline{x}$ er en konstant, og $x_1$ og $x_2$ er to variabler.

a. ) Totaldifferensier uttrykket
<div class="answer hidden">
$$\Delta \overline{x} = f'_{x_1}(x_1,x_2)\Delta x_1 + f'_{x_2}(x_1,x_2)\Delta x_2 = 0 $$
</div>
b. ) Vis så at det er mulig å skrive dette som 
$$
-\frac{\Delta x_{2}}{\Delta x_{1}}  = \frac{f'_{x_{1}}}{f'_{x_{2}}}
$$
<div class="answer hidden">
$$f'_{x_2}(x_1,x_2)\Delta x_2 =- f'_{x_1}(x_1,x_2)\Delta x_1 $$
$$\frac{\Delta x_2}{\Delta x_1} = -\frac{f'_{x_1}(x_1,x_2)}{f'_{x_2}(x_1,x_2)}$$
$$-\frac{\Delta x_2}{\Delta x_1} = \frac{f'_{x_1}(x_1,x_2)}{f'_{x_2}(x_1,x_2)}$$
</div>

## Del III: System av ligninger og Lagranges metode

### System av likninger
Løs systemet av likninger nedenfor for $x_1$ og $x_2$
\begin{eqnarray*}
\frac{x_2}{x_1} = 2  \\
10x_{1}+5x_{2}=40
\end{eqnarray*}
<div class="answer hidden">
Vi kan løse det første uttrykket for $x_2$
$$
x_2 = 2x_1  
$$
Ved å sette inn i det andre uttrykket og løse for $x_1$
$$
10x_{1}+5(2x{_1})=40 
$$
$$
x_{1}=\frac{40}{20}=2
$$
Som deretter kan løses for $x_2$ ved å sette tilbake til det først (eller andre) uttrykket:
$$
x_2 = 2\cdot 2= 4  \\
$$
</div>

### Lagranges metode
Anta at vi har at $u(x_1,x_2)=10x_1x_2$ og at $10x_{1}+5x_{2}=40$

a. ) Vis ved bruk av Lagrange-metode at dette gir opphav til systemet av ligninger vist ovenfor
<div class="answer hidden">
Maks
\begin{equation*}
u(x_1,x_2)=10x_1x_2
\end{equation*}
Gitt at
\begin{equation*}
10x_{1}+5x_{2}=40
\end{equation*}
Lagrangefunksjonen vil derfor være gitt ved
\begin{equation*}
L(x_1,x_2) = 10x_1x_2 - \lambda(10x_{1}+5x_{2}-40)
\end{equation*}
De to første ordens betingelsene vil være gitt ved:
\begin{eqnarray*}
L'_{x_1}=10x_2 - \lambda 10 = 0 \\
L'_{x_2}=10x_1 - \lambda 5 = 0 
\end{eqnarray*}
Som sammen med budsjettbetingelsen gir oss to likninger til løsing av to ukjente, $x_{1}$, $x_{2}$:
\begin{eqnarray*}
\frac{x_2}{x_1} = 2  \\
10x_{1}+5x_{2}=40
\end{eqnarray*}
</div>

<button id="show-all-answers">Vis svar</button>
<p class="answer hidden">
</p>

<style>
  .answer {
    color: blue;
  }
</style>
<script>
const answerToggles = document.querySelectorAll(".answer");
const showAllButton = document.getElementById("show-all-answers");

showAllButton.addEventListener("click", () => {
  answerToggles.forEach(answer => {
    answer.classList.toggle("hidden");
  });
});
</script>

::: {.content-visible when-profile="internal"}

:::

