---
title: ""
---


```{r, echo=F, warning=F, message=F, eval=T, results='hide'}
library(dplyr)
library(dplyr)
library(ggplot2)
library(econocharts)
md <- jsonlite::fromJSON(paste0(rprojroot::find_rstudio_root_file(),"/data-raw/metadata.json"))
## ../data-raw/metadata.json
##source(paste0(rprojroot::find_rstudio_root_file(),'/forelesninger/econplot.R'))
#source(paste0(rprojroot::find_rstudio_root_file(),'/forelesninger/timeplan.R'))
```

### Obligatorisk innleveringsoppgaver

Utlevert: **`r md$kursg$arbkutl`**.

Innleveringsfrist: **`r md$kursg$arbkinl`**.


```{r, echo=FALSE, results='asis',warning=F}
app1_fil <- paste0("/home/joernih/homepageJIH/nonpublic/templates/mikro/Arbeidskrav_SFB10816_Mikro_2024_V.qmd")
text <- readLines(app1_fil)
cat(knitr::knit_child(text = paste(text[25:length(text)], collapse = "\n"), quiet = TRUE))
```

::: {.content-visible when-profile="internal"}

<button id="show-all-answers">Vis svar</button>

<style>
  .answer {
    color: blue;
  }
</style>
<script>
const answerToggles = document.querySelectorAll(".answer");
const showAllButton = document.getElementById("show-all-answers");

showAllButton.addEventListener("click", () => {
  answerToggles.forEach(answer => {
    answer.classList.toggle("hidden");
  });
});
</script>

:::

<!--
[Trykk her for pdf-versjon]()
-->

